# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            清风抚柳
tagline:          '博客'
description:      '非淡泊无以明志，非宁静无以致远～'
avatar:           http://dashgeng.github.io/public/img/me.jpg
url:              http://dashgeng.github.io
baseurl:          /

author:
  name:           '耿大帅 (DashGeng)'
  url:            http://dashgeng.github.io

paginate:         5

# Custom vars
version:          

github:
  repo:           https://github.com/dashgeng
