# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            清风
tagline:          '技术博客'
description:      '我是一名 iOS 软件研发工程师。'
url:              http://dashgeng.github.io
baseurl:          /

author:
  name:           '耿大帅 (DashGeng)'
  url:            http://dashgeng.github.io

paginate:         5

# Custom vars
version:          

github:
  repo:           https://github.com/dashgeng
